title: User guide Kuirl
description: The whole user documentation for the generic Knora web app
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dhlab-basel.github.io" # the base hostname & protocol for your site

permalink: pretty

# Enable or disable the site search
search_enabled: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

theme: just-the-docs
